### ISSUE TITLE
Update "DGX" to be DGX2.0 token instead of the old DGX1.0

### ISSUE THREAD

**Issue by mrenoon** [ethereum-lists/tokens#101]
The old DGX1.0 token should be labeled as "DGX1", and DGX2.0 should be added as "DGX".

### Details of DGX 2.0 token, as taken from [etherscan](https://etherscan.io/token/0x4f3afec4e5a3f2a6a1a411def7d7dfe50ee057bf):
* Address: 0x4f3afec4e5a3f2a6a1a411def7d7dfe50ee057bf
* Symbol: DGX
* Decimals: 9

**Comment by ligi** [comment]
closed via #102
