### ISSUE TITLE
broken www link in desc

### ISSUE THREAD

**Issue by IRMkz** [ethereum-lists/tokens#143]
"Usage: TREZOR - they even import via IPFS ;-)" that http link is not working now

**Comment by ligi** [comment]
Thanks - yea something seems to have changed there - thanks for reporting!

**Comment by ligi** [comment]
Fixed the link - need to dig a bit deeper later though - seems to have moved to some submodule. Don't have time to dig through the changes now - just pointed to where this file was last existing. Thanks for reporting!
