### ISSUE TITLE
Indicate that a token has launched a mainnet

### ISSUE THREAD

**Issue by matejcik** [ethereum-lists/tokens#201]
there is currently no indication in the data that a token has launched a mainnet.

This seems to me to call for a new kind of entry in `"deprecation"` section, AND a new metadata entry somewhere other, because these two can be independent. Maybe there is a mainnet but the token is still tradeable? (in that case, the mainnet info is purely informative; in case of deprecation, it should mark the token as something like "do not trade")

what sort of information can we even have about a mainnet? perhaps just a boolean flag, `has_mainnet`?

so many questions

**Comment by ligi** [comment]
I don't yet see the point of this flag. If it is a token on mainnet - then it has launched mainnet.

**Comment by matejcik** [comment]
well there's a bunch of tokens leaving the Ethereum platform for their own.
E.g., I can't tell from [this](defs/ethereum/tokens/tokens/eth/0x86Fa049857E0209aa7D9e616F7eb3b3B78ECfdb0.json) that the EOS token is dead, and that it is because it has launched its own mainnet and did a token exchange

**Comment by matejcik** [comment]
in general, we might want a way to mark tokens as inactive?

**Comment by ligi** [comment]
ah now I see - perhaps it would then just be best to add a chain field to deprecation - is then a number with the chainID. Can also help when projects migrate to eth 2.0

**Comment by ligi** [comment]
> in general, we might want a way to mark tokens as inactive?

the deprecation field is a way to mark tokens as inactive and guide users to the new token (if any)

**Comment by matejcik** [comment]
> ah now I see - perhaps it would then just be best to add a chain field to deprecation - is then a number with the chainID. Can also help when projects migrate to eth 2.0

That is a good idea in any case. But i don't think the new network is guaranteed to be eth-compatible, so it might not have a chain-id.

> > in general, we might want a way to mark tokens as inactive?
> 
> the deprecation field is a way to mark tokens as inactive and guide users to the new token (if any)

isn't the `new_address` field mandatory?

But yes, i'd expect the deprecation section to be this. Perhaps a deprecation with just an announcement, maybe a special value `migration_type: none` or something?

---

Also consider e.g. QTUM or BNB, which seem to have ERC20 tokens active at the same time as their mainnets. Also consider Tether which is originally an OMNI token but launched an ERC20 variant. This seems to be a usecase for a new section, something like `"platforms"`? Which would probably be sort-of unstructured set of names/links to the same token on other platforms?

**Comment by ligi** [comment]
> That is a good idea in any case. But i don't think the new network is guaranteed to be eth-compatible, so it might not have a chain-id.

maybe we can do it the same as incubed does - some  context https://github.com/ethereum-lists/chains/issues/29

> isn't the new_address field mandatory?

just made it optional
