### ISSUE TITLE
build fails on Arch linux with openJDK

### ISSUE THREAD

**Issue by TripleSpeeder** [ethereum-lists/tokens#225]
Preface: I have no experience at all with gradle & kotlin, so bear with me if it is a stupid error :)

What i did:
 1. checkout project
 1. run "./gradlew build"

> Task :compileTestKotlin FAILED
> w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/michael/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.2.71/7512db3b3182753bd2e48ce8d345abbadc40fe6b/kotlin-reflect-1.2.71.jar (version 1.2)
    /home/michael/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.21/4bcc2012b84840e19e1e28074284cac908be0295/kotlin-stdlib-1.3.21.jar (version 1.3)
    /home/michael/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.21/f30e4a9897913e53d778f564110bafa1fef46643/kotlin-stdlib-common-1.3.21.jar (version 1.3)
> w: Consider providing an explicit dependency on kotlin-reflect 1.3 to prevent strange errors
> w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (2, 12): Unresolved reference: junit
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (7, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (14, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (21, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (29, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (37, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (44, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (51, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (58, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (65, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (73, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (81, 6): Unresolved reference: Test
> e: /home/michael/WebstormProjects/tokens/src/test/kotlin/TheTokenChecker.kt: (88, 6): Unresolved reference: Test
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileTestKotlin'.
>  Compilation error. See log for more details

This is running on Arch linux with openJDK:
> openjdk version "11.0.3" 2019-04-16
> OpenJDK Runtime Environment (build 11.0.3+4)
> OpenJDK 64-Bit Server VM (build 11.0.3+4, mixed mode)

**Comment by ligi** [comment]
thanks for reporting - fixed - will now also be catched by the ci
