### ISSUE TITLE
Symbol constraints

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/tokens#31]
especially after: https://github.com/walleth/walleth/issues/210 I think decimals should really be limited

constraint to perhaps use:
 - no "(" or ")"
 - no space

cc @tayvano

**Comment by tayvano** [comment]
Fine by me. On your UI you could also do something like if token symbol contains a space, make everything after the space font-size: 8px (or something)

I wish there was a better way to handle duplicate token symbols in general but 🤷

**Comment by ligi** [comment]
I think we should really separate this - the name is what distinguishes coins with the same symbol - that can then be displayed in 8px next to the symbol
