### ISSUE TITLE
Duplicate token symbols (from MEW import?)

### ISSUE THREAD

**Issue by wbobeirne** [ethereum-lists/tokens#32]
Both of these are "DOW":

* https://github.com/ethereum-lists/tokens/blob/master/tokens/eth/0x76974C7B79dC8a6a109Fd71fd7cEb9E40eff5382.json
* https://github.com/ethereum-lists/tokens/blob/master/tokens/eth/0xEEF6E90034eEa89E31Eb4B8eaCd323F28A92eaE4.json

Looks like one just came in from the MEW import. Might need to find a way to de-dupe these before importing.

**Comment by ligi** [comment]
yea - but seems this are really 2 different coins both seem to be "active" judging transactions on etherscan. I do not think we get token symbols unique the rate they pop up. The name needs to distinguish then IMHO

**Comment by wbobeirne** [comment]
Yeah, there definitely have been a lot of collisions with how often these pop up. I guess the question is, who's going to be the source of truth? I don't think it's reasonable to allow for these collisions, since a large number of services use the symbol as a unique identifier, which would make this set of tokens incompatible with that methodology. And since established tokens have sometimes had to swap their contract address, you can't use that as a point of truth either.

I don't think name is good enough to rely on, because it's not a very effective way for two services to communicate between each other. If I make a request about "Request Network" but you have it as "Request", it might get missed. I think symbol is the only succinct unique identifier that shouldn't change during the lifetime of a token.

Whether or not you want to be the arbiter of symbol conflicts is of course up to you, but I think if you're OK with conflicts remaining, you should have a warning about that, and provide some guidance on how to distinguish between two tokens.

Personally I'd like to see us getting to a point where the community rejects collisions. If there's an established token out there that has a symbol, we shouldn't be allowing another token to add confusion by using that token. And if two emerge at around the same time then maybe longest chain of uses wins? Distributed consensus? Seems appropriate.

**Comment by sprinklenet** [comment]
Why not use the symbol + (name) format? It's easier to immediately understand which token you're interacting with. The current method of SYMBOL + NUMBER gives a normal user no way knowing which token she's interacting with...

**Comment by sprinklenet** [comment]
Distributed consensus is a good idea but in practice that's a long ways off...

**Comment by ligi** [comment]
what do you mean with symbol+number?

**Comment by sprinklenet** [comment]
The practice of appending a number after the symbol if there's a collision/conflict.

For example, SGT 1 vs. SGT 2.  IMO, the numbers don't give enough context compared to, say, "SGT (SelfieYo Gold Token)"

**Comment by ligi** [comment]
ACK - you should bring this up in the myCrypto issue tracker then

**Comment by matejcik** [comment]
currently the following symbols have duplicates:
OHNI, KEY, DOW, EDU, PRPS, UMKA, FLMC, SKRP, HOT, GUP, DUBI, OPEN, SMT, GANA, KC, SS, VIBEX, WOLK, SGT, DRP, NONE, WHO, LEMO, CDX, COSS, PLAY, REP, CARD, FUCK, JBX

Some of these are testnet-only, others seem to be the same token on a new address? Yet others (SMT) seem to be completely different tokens.

In Trezor, the usecase is to visibly distinguish tokens on the Trezor device: when you confirm a transaction for 1 SGT, it should be enough for the user to know what they're sending. For this, adding numbers is perfectly sufficient (as long as the token advertises itself with the right symbol ofc).
But having duplicate symbols defeats that, even in case of updated symbol addresses (where using a name to de-dupe wouldn't help anyway.)

So for now at least, we are dropping the duplicate tokens from support list completely.

**Comment by ligi** [comment]
Thanks @matejcik - how do you determine which token to drop in case of the duplicates? Use the one with more traffic? 
This is a really nasty problem - I understand your decision to drop it now. Would there be space at least on model T to also show the name?

Added this also as an agenda item to the wallet developers ring (https://github.com/ethereum-magicians/scrolls/wiki/Wallet-Ring) - perhaps good ideas come up there. Would also be nice to have someone from TREZOR inside this ring!

**Comment by matejcik** [comment]
We drop both (or all) duplicates.
On model T, we *could* show the name, but again, that will not help in cases where the name is also identical (or humanly-identical, as in "JBX" vs "JBOX", "CDX" and "Carbon Dollar X", or "FinallyUsableCryptoKarma" vs "Finally Usable (...)")

(btw is it possible to determine which is the "old" version and which is "new" in those cases? if so, we could only drop the old contract and keep the new. I looked into the FUCK token, because of the name :) and apparently there's an ongoing fork and they want to change the symbol name afterwards? Perhaps the other tokens should do the same thing?)

In the currently released firmwares, the dups are still supported. I discovered the problem only a couple days ago and we will be dropping support in upcoming updates.

Also, to clarify: we don't have our own ethereum wallet, we rely on MEW and MyCrypto's Trezor support. "Supported" means that you can see the symbol on screen; when not supported, you can still sign transactions, but you get a warning about unknown token.

re wallet ring, I can see Pavol Rusnak on the list .) so there's that.

**Comment by ligi** [comment]
> We drop both (or all) duplicates. 

thats fair

> On model T, we could show the name, but again, that will not help in cases where the name is also identical (or humanly-identical, as in "JBX" vs "JBOX", "CDX" and "Carbon Dollar X", or "FinallyUsableCryptoKarma" vs "Finally Usable (...)")

What I could do on CI side: I fail the build by default if there is a token with the same name that has a date (#116) that is before the date of the token then the metadata needs a separate field (e.g. "duplicates" - that points to the previous tokens.) Then PRs must be checked that the name is not similar to humans (I think this cannot be automated - we must check this via human brains.

> re wallet ring, I can see Pavol Rusnak on the list .) so there's that.

He is just under potential - I added him there. So far no one from TREZOR confirmed and I can understand when Pavol has different priorities ;-)
