### ISSUE TITLE
Add optional field to mark token as suspicious

### ISSUE THREAD

**Issue by 409H** [ethereum-lists/tokens#369]
The end goal is to have an optional `boolean` field called `suspicious` which will mark the token as suspicious. This will be tracked with the git commit but will be used in (hopefully) good faith to mark tokens that are not the official ones as suspicious - such as fake governance tokens.

See https://twitter.com/sniko_/status/1279874748546154499 for more information

**Comment by ligi** [comment]
Good idea.

**Comment by ligi** [comment]
implementation in #370 - just wondering if instead of a boolean field we should add some context why it is suspicious (like a URL as we add for deprecation)

**Comment by 409H** [comment]
I think "as well as", instead of "instead of" would be better? It would allow a boolean answer but also offer more details in a second field as to why

**Comment by ligi** [comment]
yea - but usually when doing this we open an object. Having 2 top level fields for the same reason does not feel good and is not consistent to the current way it is. And then the question is if we need the boolean as when the object is there it would always be true which feels redundant.

**Comment by 409H** [comment]
Ah yes, good point. Let's do your plan then, that makes the most sense

**Comment by ligi** [comment]
Great! But actually looking at it when implementing it a:

`suspicious: {}`

looks a bit bad and I got a better idea. What do you think about having it like this:

`redFlags: [{"type":suspisious"}]`

when no URL provided and:

`redFlags: [{"type":suspisious","url":"http://myURL"}]`

when the URL was provided. I think this also adds some more options for the future.

**Comment by 409H** [comment]
LGTM!

**Comment by ligi** [comment]
ok - did it this way - just change to red_flags for consistency with the other fields
