### ISSUE TITLE
kontinuum/run fails

### ISSUE THREAD

**Issue by TheAbyss-dev** [ethereum-lists/tokens#396]
https://github.com/ethereum-lists/tokens/pull/395
the run job failed on this PR (though the issue seems to be with an earlier commit)
and our PR as a result is still not reflected in Trezor

**Comment by TheAbyss-dev** [comment]
https://github.com/ethereum-lists/tokens/pull/395/commits/6539b5168776050754c9be8f3b888fa4d19427a8

**Comment by TheAbyss-dev** [comment]
this is my commit

**Comment by TheAbyss-dev** [comment]
@409H @tayvano @ligi

**Comment by ligi** [comment]
Sorry - was a bit in holiday - needed some time off the computer. But I do not get the connection you make between the kontinuum failure and TREZOR not including the tokens. Was there a TREZOR release in between?

**Comment by TheAbyss-dev** [comment]
@ligi in your docs its written that TREZOR imports data via IPFS and the IPFS build fails since a few PR's ago. 
I see that the name change is applied on MyCrypto, but still don't see it on TREZOR
https://trezor.io/coins/#ABYSS
There's still an incorrect token name there

**Comment by ligi** [comment]
ok - I see - fixed the CI
