### ISSUE TITLE
Please update ETHMNY logo 0xbf4a2ddaa16148a9d0fa2093ffac450adb7cd4aa

### ISSUE THREAD

**Issue by franknakamo** [ethereum-lists/tokens#445]
Link for logo
ETHMNY contract [address:0xbf4a2ddaa16148a9d0fa2093ffac450adb7cd4aa]([url](url))

https://drive.google.com/file/d/12BfvXbG1-m8FpdLzD9bKS9K1cnf-GNXq/view?usp=drivesdk
![Ethmny logo](https://user-images.githubusercontent.com/48871196/101589171-877a5980-39ad-11eb-9a86-9c07acbb7369.png)
[https://drive.google.com/file/d/12BfvXbG1-m8FpdLzD9bKS9K1cnf-GNXq/view?usp=drivesdk(url)

**Comment by ligi** [comment]
Please make a PullRequest
