### ISSUE TITLE
Old contract address for the ANT token in the Next wallet

### ISSUE THREAD

**Issue by Tomm-y** [ethereum-lists/tokens#477]
I understand that this is not the top priority, but just for you to know, in the case of ANT, the Next wallet only has the old contract address: 0x960b236A07cf122663c4303350609A66A7B288C0 - (and it is not marked as "old") 

Due to that, one of the customers has sent an old ANT token to an exchange, which now has trouble with recovering it. - (They should be able to do that without any problems, although, it would be better to prevent this from happening)

Trezor Suite, however, recognizes the new token. The problem is, therefore, only within the Next wallet.

**Comment by ligi** [comment]
What is the correlation between the next-wallet and this repo?

**Comment by Tomm-y** [comment]
Contract addresses for next-wallet used to be pulled from this repo. Am I missing some changes?

**Comment by ligi** [comment]
You must ask the next-wallet team then. Feel free to @ / cc me. Did not even know they use this repo.
