### ISSUE TITLE
SNX token has an outdated contract address in the Trezor Suite wallet.

### ISSUE THREAD

**Issue by Tomm-y** [ethereum-lists/tokens#490]
The users of Suite wallet report that it doesn't load their SNX tokens. Considering that the token is rank 27 on the CMC, it should be updated.

I'm unsure of what contract address is specified currently for the SNX token, however, the up to date contract address is: 0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f

**Comment by ligi** [comment]
seems in this repo 0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F is used so trezor just needs to update
