### ISSUE TITLE
Adding BEP20 (BSC) tokens

### ISSUE THREAD

**Issue by Vasilii79** [ethereum-lists/tokens#525]
Hello, kindly inform is it possible to add BEP20 (BSC) tokens into Trezor's list of Supported coins & tokens?
Into This list https://trezor.io/coins/

**Comment by ligi** [comment]
do they have a chainID? Not sure about BSC as I am not a BSC user.

**Comment by Vasilii79** [comment]
> do they have a chainID? Not sure about BSC as I am not a BSC user.

Yes, Binance Smart Chain has chainID. Mainnet(ChainID 0x38, 56 in decimal)
https://docs.binance.org/smart-chain/developer/rpc.html
