### ISSUE TITLE
Merged Create 0xe6D2a9fCD946E07826C6cdd919DA04763eA4D812.json, but did not end up in the website Token lists

### ISSUE THREAD

**Issue by bruhtokeno** [ethereum-lists/tokens#612]
Hi, I am the creator of Create 0xe6D2a9fCD946E07826C6cdd919DA04763eA4D812.json. The file was merged about a week ago, but I do not see the token’s name on the list of supported tokens on Trezor’s website. When will Bruh go onto the website’s list?

**Comment by ligi** [comment]
please ask trezor
