### ISSUE TITLE
HAV tokens - address change

### ISSUE THREAD

**Issue by CryptoToit** [ethereum-lists/tokens#94]
I noticed that the HAV tokens was replaced with 'new' ones in my ethereum address. 

It changed from this contract 0xf244176246168f24e3187f7288edbca29267739b to this one 0xc011a72400e58ecd99ee497cf89e3775d4bd732f. 

When accessing my ETH wallet via MyCrypto it shows the original HAV as 0 and does not 'see' the new ones. (I know it is there)

I logged the issue with MyCrypto but they referred me here so I just wanted to raise it.

Thanks

**Comment by ligi** [comment]
Do you have a official blog-post or something in this direction that documents the change?

**Comment by CryptoToit** [comment]
No, nothing. It is also quite a surprise to me.. I just noticed it in my Ethereum account. 

I have on 2 occasions transferred HAV to my ETH wallet:


and



I then on a later date noticed this (total = sum of the 2 above):



They have different contract addresses.

When I do a "coin scan” on MyCrypto it finds the HAV token but it shows as 0. 


Hope this helps…?

**Comment by ligi** [comment]
just got a reply - here the blog post:

https://blog.havven.io/havs-now-have-a-new-contract-address-c870d7db7ad8
